export class MockData {
    static agGridColumnDefs_EdaTower: any[] = [
        {
            headerName: '',
            field: '#',
            width: 85,
            checkboxSelection: true
        },
        {
            headerName: 'Status',
            field: 'statusFlag',
            width: 80
        },
        {
            headerName: 'Entity Name',
            field: 'entityName',
            width: 200
        },
        {
            headerName: 'Business Class',
            field: 'businessClass',
            width: 100
        },
        {
            headerName: 'Policy Year',
            field: 'policyYear',
            width: 100
        },
        {
            headerName: 'Policy Effective Date',
            field: 'policyEffectiveDate',
            width: 150
        },
        {
            headerName: 'Source Type',
            field: 'sourceType',
            width: 150
        },
        {
            headerName: 'Source Description',
            field: 'sourceDescription',
            width: 100
        },
        {
            headerName: 'As At Date',
            field: 'asAtDate',
            width: 100
        },
        {
            headerName: 'Max Tower Limit',
            field: 'maxTowerLimit',
            width: 100
        },
        {
            headerName: 'Total Primary',
            field: 'primaryExposure',
            width: 100
        },
        {
            headerName: 'Total Exposure',
            field: 'totalExposure',
            width: 100
        },
        {
            headerName: 'Priority',
            field: 'priority',
            width: 100
        },
        {
            headerName: 'Tower Complete',
            field: 'isTowerComplete',
            width: 100
        },
        {
            headerName: 'Renewal',
            field: 'isRenewal',
            width: 100
        },
        {
            headerName: 'Updated By',
            field: 'fullName',
            width: 100
        },
        {
            headerName: 'Updated Date',
            field: 'modifiedDate',
            width: 100
        },
        {
            headerName: 'Modified',
            field: 'modifiedFlag',
            width: 100
        },
        {
            headerName: 'Excel',
            field: 'excel',
            width: 100
        },
        {
            headerName: 'Sheet',
            field: 'sheet',
            width: 100
        }
    ];

    static agGridRowData_EdaTower: any[] = [
        {
            id: 36,
            insuredName: 'Microsoft Corporation',
            entityTicker: 'MSFT',
            policyEffectiveDate: '07/20/2016',
            policyEndDate: '6/13/2017',
            primaryBroker: 'Aon',
            primarySIRDeductible: 25000000.0,
            entityFactSetID: '05V1YY-E',
            entityName: 'MICROSOFT LTD',
            ultimateParentName: 'MICROSOFT CORP',
            exposureSource: '',
            asAtDate: '01/01/2017',
            sourceType: 'Audit',
            sourceDescription: 'asadullahkhanghalib2.',
            policyYear: 2016,
            businessClass: 'Hedge Fund',
            isTowerComplete: 'No',
            manuallyTrackedPrimary: '',
            manuallyTrackedExposure: '',
            excel: 'Test-Nishant.xlsx',
            sheet: 'Template$',
            priority: true,
            maxTowerLimit: 120000000.0,
            totalExposure: 1925000.0,
            primaryExposure: 75000000.0,
            curencyCode: 'USD',
            createdBy: 'nkhandelwal',
            modifiedBy: 'nkhandelwal',
            fullName: 'Khandelwal, Naveen',
            modifiedDate: '05/04/2018 10:20 AM',
            modifiedFlag: 'Yes',
            createdDate: '7/11/2017',
            statusFlag: 'Complete',
            status: 'V',
            isRenewal: false
        },
        {
            id: 36,
            insuredName: 'Microsoft Corporation',
            entityTicker: 'MSFT',
            policyEffectiveDate: '07/20/2016',
            policyEndDate: '6/13/2017',
            primaryBroker: 'Aon',
            primarySIRDeductible: 25000000.0,
            entityFactSetID: '05V1YY-E',
            entityName: 'MICROSOFT LTD',
            ultimateParentName: 'MICROSOFT CORP',
            exposureSource: '',
            asAtDate: '01/01/2017',
            sourceType: 'Audit',
            sourceDescription: 'asadullahkhanghalib2.',
            policyYear: 2016,
            businessClass: 'Hedge Fund',
            isTowerComplete: 'No',
            manuallyTrackedPrimary: '',
            manuallyTrackedExposure: '',
            excel: 'Test-Nishant.xlsx',
            sheet: 'Template$',
            priority: true,
            maxTowerLimit: 120000000.0,
            totalExposure: 1925000.0,
            primaryExposure: 75000000.0,
            curencyCode: 'USD',
            createdBy: 'nkhandelwal',
            modifiedBy: 'nkhandelwal',
            fullName: 'Khandelwal, Naveen',
            modifiedDate: '05/04/2018 10:20 AM',
            modifiedFlag: 'Yes',
            createdDate: '7/11/2017',
            statusFlag: 'Complete',
            status: 'V',
            isRenewal: false
        },
        {
            id: 36,
            insuredName: 'Microsoft Corporation',
            entityTicker: 'MSFT',
            policyEffectiveDate: '07/20/2016',
            policyEndDate: '6/13/2017',
            primaryBroker: 'Aon',
            primarySIRDeductible: 25000000.0,
            entityFactSetID: '05V1YY-E',
            entityName: 'MICROSOFT LTD',
            ultimateParentName: 'MICROSOFT CORP',
            exposureSource: '',
            asAtDate: '01/01/2017',
            sourceType: 'Audit',
            sourceDescription: 'asadullahkhanghalib2.',
            policyYear: 2016,
            businessClass: 'Hedge Fund',
            isTowerComplete: 'No',
            manuallyTrackedPrimary: '',
            manuallyTrackedExposure: '',
            excel: 'Test-Nishant.xlsx',
            sheet: 'Template$',
            priority: true,
            maxTowerLimit: 120000000.0,
            totalExposure: 1925000.0,
            primaryExposure: 75000000.0,
            curencyCode: 'USD',
            createdBy: 'nkhandelwal',
            modifiedBy: 'nkhandelwal',
            fullName: 'Khandelwal, Naveen',
            modifiedDate: '05/04/2018 10:20 AM',
            modifiedFlag: 'Yes',
            createdDate: '7/11/2017',
            statusFlag: 'Complete',
            status: 'V',
            isRenewal: false
        },
        {
            id: 36,
            insuredName: 'Microsoft Corporation',
            entityTicker: 'MSFT',
            policyEffectiveDate: '07/20/2016',
            policyEndDate: '6/13/2017',
            primaryBroker: 'Aon',
            primarySIRDeductible: 25000000.0,
            entityFactSetID: '05V1YY-E',
            entityName: 'MICROSOFT LTD',
            ultimateParentName: 'MICROSOFT CORP',
            exposureSource: '',
            asAtDate: '01/01/2017',
            sourceType: 'Audit',
            sourceDescription: 'asadullahkhanghalib2.',
            policyYear: 2016,
            businessClass: 'Hedge Fund',
            isTowerComplete: 'No',
            manuallyTrackedPrimary: '',
            manuallyTrackedExposure: '',
            excel: 'Test-Nishant.xlsx',
            sheet: 'Template$',
            priority: true,
            maxTowerLimit: 120000000.0,
            totalExposure: 1925000.0,
            primaryExposure: 75000000.0,
            curencyCode: 'USD',
            createdBy: 'nkhandelwal',
            modifiedBy: 'nkhandelwal',
            fullName: 'Khandelwal, Naveen',
            modifiedDate: '05/04/2018 10:20 AM',
            modifiedFlag: 'Yes',
            createdDate: '7/11/2017',
            statusFlag: 'Complete',
            status: 'V',
            isRenewal: false
        },
        {
            id: 36,
            insuredName: 'Microsoft Corporation',
            entityTicker: 'MSFT',
            policyEffectiveDate: '07/20/2016',
            policyEndDate: '6/13/2017',
            primaryBroker: 'Aon',
            primarySIRDeductible: 25000000.0,
            entityFactSetID: '05V1YY-E',
            entityName: 'MICROSOFT LTD',
            ultimateParentName: 'MICROSOFT CORP',
            exposureSource: '',
            asAtDate: '01/01/2017',
            sourceType: 'Audit',
            sourceDescription: 'asadullahkhanghalib2.',
            policyYear: 2016,
            businessClass: 'Hedge Fund',
            isTowerComplete: 'No',
            manuallyTrackedPrimary: '',
            manuallyTrackedExposure: '',
            excel: 'Test-Nishant.xlsx',
            sheet: 'Template$',
            priority: true,
            maxTowerLimit: 120000000.0,
            totalExposure: 1925000.0,
            primaryExposure: 75000000.0,
            curencyCode: 'USD',
            createdBy: 'nkhandelwal',
            modifiedBy: 'nkhandelwal',
            fullName: 'Khandelwal, Naveen',
            modifiedDate: '05/04/2018 10:20 AM',
            modifiedFlag: 'Yes',
            createdDate: '7/11/2017',
            statusFlag: 'Complete',
            status: 'V',
            isRenewal: false
        },
        {
            id: 36,
            insuredName: 'Microsoft Corporation',
            entityTicker: 'MSFT',
            policyEffectiveDate: '07/20/2016',
            policyEndDate: '6/13/2017',
            primaryBroker: 'Aon',
            primarySIRDeductible: 25000000.0,
            entityFactSetID: '05V1YY-E',
            entityName: 'MICROSOFT LTD',
            ultimateParentName: 'MICROSOFT CORP',
            exposureSource: '',
            asAtDate: '01/01/2017',
            sourceType: 'Audit',
            sourceDescription: 'asadullahkhanghalib2.',
            policyYear: 2016,
            businessClass: 'Hedge Fund',
            isTowerComplete: 'No',
            manuallyTrackedPrimary: '',
            manuallyTrackedExposure: '',
            excel: 'Test-Nishant.xlsx',
            sheet: 'Template$',
            priority: true,
            maxTowerLimit: 120000000.0,
            totalExposure: 1925000.0,
            primaryExposure: 75000000.0,
            curencyCode: 'USD',
            createdBy: 'nkhandelwal',
            modifiedBy: 'nkhandelwal',
            fullName: 'Khandelwal, Naveen',
            modifiedDate: '05/04/2018 10:20 AM',
            modifiedFlag: 'Yes',
            createdDate: '7/11/2017',
            statusFlag: 'Complete',
            status: 'V',
            isRenewal: false
        },
        {
            id: 36,
            insuredName: 'Microsoft Corporation',
            entityTicker: 'MSFT',
            policyEffectiveDate: '07/20/2016',
            policyEndDate: '6/13/2017',
            primaryBroker: 'Aon',
            primarySIRDeductible: 25000000.0,
            entityFactSetID: '05V1YY-E',
            entityName: 'MICROSOFT LTD',
            ultimateParentName: 'MICROSOFT CORP',
            exposureSource: '',
            asAtDate: '01/01/2017',
            sourceType: 'Audit',
            sourceDescription: 'asadullahkhanghalib2.',
            policyYear: 2016,
            businessClass: 'Hedge Fund',
            isTowerComplete: 'No',
            manuallyTrackedPrimary: '',
            manuallyTrackedExposure: '',
            excel: 'Test-Nishant.xlsx',
            sheet: 'Template$',
            priority: true,
            maxTowerLimit: 120000000.0,
            totalExposure: 1925000.0,
            primaryExposure: 75000000.0,
            curencyCode: 'USD',
            createdBy: 'nkhandelwal',
            modifiedBy: 'nkhandelwal',
            fullName: 'Khandelwal, Naveen',
            modifiedDate: '05/04/2018 10:20 AM',
            modifiedFlag: 'Yes',
            createdDate: '7/11/2017',
            statusFlag: 'Complete',
            status: 'V',
            isRenewal: false
        },
        {
            id: 36,
            insuredName: 'Microsoft Corporation',
            entityTicker: 'MSFT',
            policyEffectiveDate: '07/20/2016',
            policyEndDate: '6/13/2017',
            primaryBroker: 'Aon',
            primarySIRDeductible: 25000000.0,
            entityFactSetID: '05V1YY-E',
            entityName: 'MICROSOFT LTD',
            ultimateParentName: 'MICROSOFT CORP',
            exposureSource: '',
            asAtDate: '01/01/2017',
            sourceType: 'Audit',
            sourceDescription: 'asadullahkhanghalib2.',
            policyYear: 2016,
            businessClass: 'Hedge Fund',
            isTowerComplete: 'No',
            manuallyTrackedPrimary: '',
            manuallyTrackedExposure: '',
            excel: 'Test-Nishant.xlsx',
            sheet: 'Template$',
            priority: true,
            maxTowerLimit: 120000000.0,
            totalExposure: 1925000.0,
            primaryExposure: 75000000.0,
            curencyCode: 'USD',
            createdBy: 'nkhandelwal',
            modifiedBy: 'nkhandelwal',
            fullName: 'Khandelwal, Naveen',
            modifiedDate: '05/04/2018 10:20 AM',
            modifiedFlag: 'Yes',
            createdDate: '7/11/2017',
            statusFlag: 'Complete',
            status: 'V',
            isRenewal: false
        },
        {
            id: 36,
            insuredName: 'Microsoft Corporation',
            entityTicker: 'MSFT',
            policyEffectiveDate: '07/20/2016',
            policyEndDate: '6/13/2017',
            primaryBroker: 'Aon',
            primarySIRDeductible: 25000000.0,
            entityFactSetID: '05V1YY-E',
            entityName: 'MICROSOFT LTD',
            ultimateParentName: 'MICROSOFT CORP',
            exposureSource: '',
            asAtDate: '01/01/2017',
            sourceType: 'Audit',
            sourceDescription: 'asadullahkhanghalib2.',
            policyYear: 2016,
            businessClass: 'Hedge Fund',
            isTowerComplete: 'No',
            manuallyTrackedPrimary: '',
            manuallyTrackedExposure: '',
            excel: 'Test-Nishant.xlsx',
            sheet: 'Template$',
            priority: true,
            maxTowerLimit: 120000000.0,
            totalExposure: 1925000.0,
            primaryExposure: 75000000.0,
            curencyCode: 'USD',
            createdBy: 'nkhandelwal',
            modifiedBy: 'nkhandelwal',
            fullName: 'Khandelwal, Naveen',
            modifiedDate: '05/04/2018 10:20 AM',
            modifiedFlag: 'Yes',
            createdDate: '7/11/2017',
            statusFlag: 'Complete',
            status: 'V',
            isRenewal: false
        },
        {
            id: 36,
            insuredName: 'Microsoft Corporation',
            entityTicker: 'MSFT',
            policyEffectiveDate: '07/20/2016',
            policyEndDate: '6/13/2017',
            primaryBroker: 'Aon',
            primarySIRDeductible: 25000000.0,
            entityFactSetID: '05V1YY-E',
            entityName: 'MICROSOFT LTD',
            ultimateParentName: 'MICROSOFT CORP',
            exposureSource: '',
            asAtDate: '01/01/2017',
            sourceType: 'Audit',
            sourceDescription: 'asadullahkhanghalib2.',
            policyYear: 2016,
            businessClass: 'Hedge Fund',
            isTowerComplete: 'No',
            manuallyTrackedPrimary: '',
            manuallyTrackedExposure: '',
            excel: 'Test-Nishant.xlsx',
            sheet: 'Template$',
            priority: true,
            maxTowerLimit: 120000000.0,
            totalExposure: 1925000.0,
            primaryExposure: 75000000.0,
            curencyCode: 'USD',
            createdBy: 'nkhandelwal',
            modifiedBy: 'nkhandelwal',
            fullName: 'Khandelwal, Naveen',
            modifiedDate: '05/04/2018 10:20 AM',
            modifiedFlag: 'Yes',
            createdDate: '7/11/2017',
            statusFlag: 'Complete',
            status: 'V',
            isRenewal: false
        },
        {
            id: 38,
            insuredName: 'Microsoft Corporation',
            entityTicker: 'MSFT',
            policyEffectiveDate: '07/01/2016',
            policyEndDate: '7/1/2017',
            primaryBroker: 'Aon',
            primarySIRDeductible: 25000000.0,
            entityFactSetID: '05V1YY-E',
            entityName: 'MICROSOFT LTD',
            ultimateParentName: 'MICROSOFT CORP',
            exposureSource: '',
            asAtDate: '11/10/2017',
            sourceType: 'Audit',
            sourceDescription: 'fatimatest',
            policyYear: 2016,
            businessClass: 'Architects and Engineers',
            isTowerComplete: 'No',
            manuallyTrackedPrimary: '',
            manuallyTrackedExposure: '',
            excel: 'Test-Nishant.xlsx',
            sheet: 'Template$',
            priority: true,
            maxTowerLimit: 120000000.0,
            totalExposure: 1925000.0,
            primaryExposure: 75000000.0,
            curencyCode: 'USD',
            createdBy: 'nkhandelwal',
            modifiedBy: 'fmukhtar',
            fullName: '',
            modifiedDate: '04/04/2018 4:04 AM',
            modifiedFlag: 'Yes',
            createdDate: '7/11/2017',
            statusFlag: 'Complete',
            status: 'V',
            isRenewal: false
        },
        {
            id: 1041,
            insuredName: 'VERIZON',
            entityTicker: 'VRZN',
            policyEffectiveDate: '07/14/2016',
            policyEndDate: '7/14/2017',
            primaryBroker: 'Aon',
            primarySIRDeductible: 24000000.0,
            entityFactSetID: '000LBJ-E',
            entityName: 'VERIZON SOUTH INC',
            ultimateParentName: 'VERIZON COMMUNICATIONS INC',
            exposureSource: '',
            asAtDate: '08/02/2017',
            sourceType: 'Market Intelligence',
            sourceDescription: 'desc',
            policyYear: 2016,
            businessClass: 'FI D&O',
            isTowerComplete: 'Yes',
            manuallyTrackedPrimary: '',
            manuallyTrackedExposure: '',
            excel: 'Verizon test1.xlsx',
            sheet: 'Template$',
            priority: true,
            maxTowerLimit: 100000000.0,
            totalExposure: 2350000.0,
            primaryExposure: 100000000.0,
            curencyCode: 'USD',
            createdBy: 'mbarua',
            modifiedBy: 'kotoole',
            fullName: "O'Toole, Karl",
            modifiedDate: '11/02/2017 4:55 PM',
            modifiedFlag: 'No',
            createdDate: '8/2/2017',
            statusFlag: 'Complete',
            status: 'V',
            isRenewal: false
        },
        {
            id: 1361,
            insuredName: 'MICROSOFT PTY LTD',
            entityTicker: 'MSFT',
            policyEffectiveDate: '07/01/2016',
            policyEndDate: '7/1/2017',
            primaryBroker: 'Aon',
            primarySIRDeductible: 25000000.0,
            entityFactSetID: '0672T0-E',
            entityName: 'MICROSOFT PTY LTD',
            ultimateParentName: 'MICROSOFT CORP',
            exposureSource: '',
            asAtDate: '08/21/2017',
            sourceType: 'Market Intelligence',
            sourceDescription: 'Market Intelligence Desc',
            policyYear: 2016,
            businessClass: 'Blended Public',
            isTowerComplete: 'No',
            manuallyTrackedPrimary: '',
            manuallyTrackedExposure: '',
            excel: 'Manual Tower Template - MICROSOFT PTY LTD.xlsx',
            sheet: 'Template$',
            priority: true,
            maxTowerLimit: 120000000.0,
            totalExposure: 2350000.0,
            primaryExposure: 100000000.0,
            curencyCode: 'USD',
            createdBy: 'rbohra',
            modifiedBy: 'rbohra',
            fullName: 'Bohra, Rashed',
            modifiedDate: '08/21/2017 10:51 AM',
            modifiedFlag: 'No',
            createdDate: '8/17/2017',
            statusFlag: 'Complete',
            status: 'V',
            isRenewal: false
        },
        {
            id: 1363,
            insuredName: 'Microsoft Corporation',
            entityTicker: 'MSFT',
            policyEffectiveDate: '07/01/2016',
            policyEndDate: '7/1/2017',
            primaryBroker: 'Aon',
            primarySIRDeductible: 25000000.0,
            entityFactSetID: '061N9F-E',
            entityName: 'MICROSOFT CANADA CO',
            ultimateParentName: 'MICROSOFT CORP',
            exposureSource: '',
            asAtDate: '08/17/2017',
            sourceType: 'Market Intelligence',
            sourceDescription: '',
            policyYear: 2016,
            businessClass: 'Cyber Liability',
            isTowerComplete: 'No',
            manuallyTrackedPrimary: '',
            manuallyTrackedExposure: '',
            excel: 'Manual Tower Template.xlsx',
            sheet: "'Sample Data$'",
            priority: true,
            maxTowerLimit: 120000000.0,
            totalExposure: 2350000.0,
            primaryExposure: 100000000.0,
            curencyCode: 'USD',
            createdBy: 'nkhandelwal',
            modifiedBy: 'nkhandelwal',
            fullName: 'Khandelwal, Naveen',
            modifiedDate: '08/17/2017 2:54 PM',
            modifiedFlag: 'No',
            createdDate: '8/17/2017',
            statusFlag: 'Complete',
            status: 'V',
            isRenewal: false
        },
        {
            id: 1370,
            insuredName: 'Microsoft Corporation',
            entityTicker: 'MSFT',
            policyEffectiveDate: '07/01/2016',
            policyEndDate: '7/1/2017',
            primaryBroker: 'Aon',
            primarySIRDeductible: 25000000.0,
            entityFactSetID: '0969H3-E',
            entityName: 'MICROSOFT KOREA CORP',
            ultimateParentName: 'MICROSOFT CORP',
            exposureSource: '',
            asAtDate: '08/18/2017',
            sourceType: 'News Article',
            sourceDescription: 'l',
            policyYear: 2016,
            businessClass: 'Blended Public',
            isTowerComplete: 'Yes',
            manuallyTrackedPrimary: '',
            manuallyTrackedExposure: '',
            excel: 'Test-Nishant.xlsx',
            sheet: 'Template$',
            priority: true,
            maxTowerLimit: 120000000.0,
            totalExposure: 2350000.0,
            primaryExposure: 100000000.0,
            curencyCode: 'USD',
            createdBy: 'nkhandelwal',
            modifiedBy: 'nkhandelwal',
            fullName: 'Khandelwal, Naveen',
            modifiedDate: '08/18/2017 9:27 AM',
            modifiedFlag: 'No',
            createdDate: '8/18/2017',
            statusFlag: 'Complete',
            status: 'V',
            isRenewal: false
        }
    ];

    static agGridColumnDefs_homeScreen: any[] = [
        {
            headerName: 'Actions',
            field: 'actions',
            width: 80
        },
        {
            headerName: 'Latest BX Status',
            field: 'latestBXStatus',
            width: 80
        },
        {
            headerName: 'LOB',
            field: 'lob',
            width: 80
        },
        {
            headerName: 'Underwriter',
            field: 'underwriter',
            width: 80
        },
        {
            headerName: 'Ceding Group',
            field: 'cedingGroup',
            width: 80
        },
        {
            headerName: 'Ceding Company',
            field: 'cedingCompany',
            width: 80
        },
        {
            headerName: 'Latest As At Date',
            field: 'latestAsAtDate',
            width: 80
        },
        {
            headerName: 'Latest BX Policy Eff. Date',
            field: 'latestBxPolicyEffDate',
            width: 80
        },
        {
            headerName: 'Latest Policy Eff. Date In Eda',
            field: 'latestPolicyEffDateInEda',
            width: 80
        },
        {
            headerName: 'Treaty Status',
            field: 'treatyStatus',
            width: 80
        },
        {
            headerName: 'Submissions',
            field: 'submissions',
            width: 80
        },
        {
            headerName: 'BX Type',
            field: 'bxType',
            width: 80
        },
        {
            headerName: 'BX Frequency',
            field: 'bxFrequency',
            width: 80
        }
    ];

    static agGridRowDefs_homeScreen: any[] = [
        {
            actions: '',
            latestBXStatus: 'Validation',
            lob: 'Headge Fund',
            underwriter: 'Karl',
            cedingGroup: 'Microsoft Ltd',
            cedingCompany: 'Microsoft Ltd',
            latestAsAtDate: '8/2/2017',
            latestBxPolicyEffDate: '8/2/2017',
            latestPolicyEffDateInEda: '8/2/2017',
            treatyStatus: 'Reserve',
            submissions: '10',
            bxType: 'new',
            bxFrequency: '5'
        },
        {
            actions: '',
            latestBXStatus: 'Validation',
            lob: 'Headge Fund',
            underwriter: 'Karl',
            cedingGroup: 'Microsoft Ltd',
            cedingCompany: 'Microsoft Ltd',
            latestAsAtDate: '8/2/2017',
            latestBxPolicyEffDate: '8/2/2017',
            latestPolicyEffDateInEda: '8/2/2017',
            treatyStatus: 'Reserve',
            submissions: '10',
            bxType: 'new',
            bxFrequency: '5'
        },
        {
            actions: '',
            latestBXStatus: 'Validation',
            lob: 'Headge Fund',
            underwriter: 'Karl',
            cedingGroup: 'Microsoft Ltd',
            cedingCompany: 'Microsoft Ltd',
            latestAsAtDate: '8/2/2017',
            latestBxPolicyEffDate: '8/2/2017',
            latestPolicyEffDateInEda: '8/2/2017',
            treatyStatus: 'Reserve',
            submissions: '10',
            bxType: 'new',
            bxFrequency: '5'
        }
    ];

    static agGridColumnDefs_NameMatching: any[] = [
        {
            headerName: 'Action',
            field: 'Action',
            width: 85,
            checkboxSelection: true
        },
        {
            headerName: 'BXENtityName',
            field: 'BXENtityName',
            width: 80
        },
        {
            headerName: 'MatchPercentage',
            field: 'MatchPercentage',
            width: 200
        },
        {
            headerName: 'MatchedName',
            field: 'MatchedName',
            width: 100
        },
        {
            headerName: 'More',
            field: 'More',
            width: 100
        },
        {
            headerName: 'CedentPolicyLimit',
            field: 'CedentPolicyLimit',
            width: 150
        },
        {
            headerName: 'PolicyGWP',
            field: 'PolicyGWP',
            width: 150
        },
        {
            headerName: 'AttachmentPoint',
            field: 'AttachmentPoint',
            width: 100
        },
        {
            headerName: 'MatchSource',
            field: 'MatchSource',
            width: 100
        }
    ];

    static agGridRowData_NameMatching: any[] = [
        {
            Action: '',
            BXENtityName: 'Microsoft',
            MatchPercentage: '100',
            MatchedName: 'Microsoft',
            More: '...',
            CedentPolicyLimit: '10000000',
            PolicyGWP: '10000',
            AttachmentPoint: '90000000',
            MatchSource: 'Raw Nmes'
        },
        {
            Action: '',
            BXENtityName: 'Microsoft',
            MatchPercentage: '100',
            MatchedName: 'Microsoft',
            More: '...',
            CedentPolicyLimit: '10000000',
            PolicyGWP: '10000',
            AttachmentPoint: '90000000',
            MatchSource: 'Raw Nmes'
        },
        {
            Action: '',
            BXENtityName: 'Microsoft',
            MatchPercentage: '100',
            MatchedName: 'Microsoft',
            More: '...',
            CedentPolicyLimit: '10000000',
            PolicyGWP: '10000',
            AttachmentPoint: '90000000',
            MatchSource: 'Raw Nmes'
        },
        {
            Action: '',
            BXENtityName: 'Microsoft',
            MatchPercentage: '100',
            MatchedName: 'Microsoft',
            More: '...',
            CedentPolicyLimit: '10000000',
            PolicyGWP: '10000',
            AttachmentPoint: '90000000',
            MatchSource: 'Raw Nmes'
        }
    ];

    static agGridColumnDefs_WF: any[] = [
        { field: 'Action', cellRenderer: 'BordereauActionsRenderer' },
        { field: 'ProcessStatus' },
        { field: 'LOB' },
        { field: 'Underwriter' },
        { field: 'CedingGroup' },
        { field: 'CedingCompany' },
        { field: 'AsAtDate' },
        { field: 'FileType' },
        { field: 'FileName' },
        { field: 'SheetName' },
        { field: 'Comments' },
        { field: 'LastUpdateDate' },
        { field: 'LastUpdatedBy' },
        { field: 'LoadDate' },
        { field: 'LoadBy' }
    ];

    static agGridRowData_WF: any[] = [
        {
            ProcessStatus: 'Completed',
            LOB: 'Prof. Liab(Cyber)',
            Underwriter: 'Markowski, Lauren',
            CedingGroup: 'Travelers Comapnies Inc.',
            CedingCompany: 'Travelers Indemnity Company.',
            AsAtDate: '4/20/2018',
            FileType: 'Final',
            FileName: 'Travelers Cyber',
            SheetName: 'Sheet1',
            Comments: 'File Comments',
            LastUpdateDate: '4/20/2018',
            LastUpdatedBy: '4/20/2018',
            LoadDate: '4/20/2018',
            LoadBy: 'sfuller'
        }
    ];
}
